### ISSUE TITLE
Corona Simulator: Packaging app takes for Ever

### ISSUE THREAD

**Issue by zi405** [coronalabs/corona-docs#100]
I am new to the SDK, when I try to build apk of demo project  corona simulator show progress bar window "Build Progress" it says Packaging app
and it takes for ever nothing even show in the console window
I don't know how to fix this issue . help is appreciated.

**Comment by Shchvova** [comment]
It takes this long only first time, depending on connection speed. After
that it would build much faster. It has to download Android SDK first time,
which is about 500 mb
