### ISSUE TITLE
Bug in sample code of gameControllers documentation

### ISSUE THREAD

**Issue by webshaker** [coronalabs/corona-docs#108]
Hello.

In section 
Handling Controller Input

in the sample code, the two lines 

    Runtime:removeEventListener( "axis", onAxisEvent )
    Runtime:removeEventListener( "key", onKeyEvent )

are useless because onAxisEvent  and onKeyEvent  are not yet defined in the script.

They should be placed into the event themseves to work correctly

    local function onKeyEvent( event )
        setDevice( event.device, event.device.displayName )
        Runtime:removeEventListener( "key", onKeyEvent )
    end
 
    local function onAxisEvent( event )
        if ( math.abs(event.normalizedValue) > 0.5 ) then
            setDevice( event.device, event.device.displayName )
            Runtime:removeEventListener( "axis", onAxisEvent )
        end
    end

**Comment by scottrules44** [comment]
Fixed in lastest docs
