### ISSUE TITLE
Documentation of Samsung IAP

### ISSUE THREAD

**Issue by jajern** [coronalabs/corona-docs#111]
This is an issue I discovered with the documentation for Samsung IAP on this page:
https://docs.coronalabs.com/plugin/samsung-iap/index.html

Towards the bottom of the page there is a note that says this permission will automatically be added: "com.samsung.android.iap.permission.BILLING".

When I build the APK for the Samsung store and uploaded, the store did not find that permission above and would not allow IAP items to be added. I resolved this by manually adding that permission to the project build.settings.

Either the build system should be adding this in and is not doing that, or consider changing the note in the documentation so users know to manually put that permission in the build.settings file.

Just incase this is not happening to other users, I am building on a MacBook Pro (16-inch, 2021) Apple M1 Max, using Solar2D build 2022.3664

Thank you.

**Comment by scottrules44** [comment]
The permission has now been added to the plugin

Thanks
Scott
