### ISSUE TITLE
build.sh in project template for Solar2D Native — iOS fails out of the box

### ISSUE THREAD

**Issue by enigmathix** [coronalabs/corona-docs#120]
To reproduce:
Follow first instruction from this page: https://docs.coronalabs.com/native/ios/index.html
Within the /Applications/Corona/Native/ folder, double click Setup Corona Native. This will create the symbolic link required for the project templates

Copy that template, and run build.sh. It fails with this error:

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /path_to_app/App/ios/build/Release-iphoneos/libplugin_library.a and /path_to_app/App/ios/build/Release-iphonesimulator/libplugin_library.a have the same architectures (arm64) and can't be in the same fat output file

This is Corona version 3677 with Xcode 12.1.

**Comment by enigmathix** [comment]
Possible solution: Plugin.xcodeproj Build Settings:
Architectures:
  Excluded Architectures:
    Debug/Release:
      Any iOS Simulator SDK: arm64

**Comment by Shchvova** [comment]
Thanks! It'll be in next build. Here's a script if you want to get it sooner.
