### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by AleCGames** [coronalabs/corona-docs#137]
Hi,
In the page about the plugin [ GPGS V3](https://docs.coronalabs.com/plugin/gpgs3/isConnected.html), when you click on the **isConnected** event link, the next page show two properties: **event.name** and **event.isError**, and when you click on **event.isError** you get the page related to the **isConnected** event. It should be **event.isConnected** istead of **event.isError**. Please, fix these because it seems there is a confusion about the listener _gpgs.isConnected(listener)_

**Comment by scottrules44** [comment]
This is fixed now; thanks for reporting!
