### ISSUE TITLE
GPGSv3 docs should mention that using Google to roll out is required

### ISSUE THREAD

**Issue by prairiewest** [coronalabs/corona-docs#139]
On the page:
https://docs.coronalabs.com/plugin/gpgs3/index.html

I think it's worth mentioning that deploying locally using "Copy to device and launch" will not work.  Instead, developers must use one of Google's testing tracks (ie: internal testing) to roll out the app to testing devices.

The hyperlink at the top of the page to "Sample" is broken, and could either be removed or pointed to:
https://github.com/solar2d/com.solar2d-plugin.gpgs.v3/tree/master/src/Corona

**Comment by sekodev** [comment]
Thank you for pointing that out. It should be fixed now.
