### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by Jedures** [coronalabs/corona-docs#142]
Can you add documentation to https://docs.coronalabs.com/plugin/index.html page of my plugin: https://github.com/solar2d/com.cleveradssolutions-plugin.cas?

**Comment by Jedures** [comment]
I want to host my documentation here(https://docs.coronalabs.com/plugin/index.html). I have documentation inside my plugin as in other of your repositories. Is it possible or what do I need to do to make it possible?

**Comment by scottrules44** [comment]
Yeah I mean https://docs.coronalabs.com/plugin/index.html I mainly for 1st party plugins i.e "com.coronalabs" or "com.solar2d".  
The page you are referring to has links plugins.solar2d.com or solar2dmarketplace.com which used to show 3rd party plugins and link to docs. The docs.coronalabs.com/plugin could get overloaded and confuse users if a bunch of 3rd parties linked their  docs.

 If you want to put your docs in your plugins.solar2d.com listing you add that link to website field of your repo
<img width="811" alt="Screenshot 2023-03-24 at 7 40 13 PM" src="https://user-images.githubusercontent.com/7820808/227668630-94c28fe6-eaa0-4fe4-b8b7-0f4036e47ecf.png">


<img width="593" alt="Screenshot 2023-03-24 at 7 42 24 PM" src="https://user-images.githubusercontent.com/7820808/227668667-d7d6c0b1-d7eb-476a-bafd-861e6b979c07.png">

**Comment by Jedures** [comment]
Hello, but I can't edit repository settings and put a link because your team created the repository for me. Can you help me with it?

**Comment by Shchvova** [comment]
What is the link?

**Comment by Jedures** [comment]
The link for the plugins is https://github.com/solar2d/com.cleveradssolutions-plugin.cas. 
The link for the documentation should be https://docs.coronalabs.com/plugin/cleveradssolutions/index.html, if I understand you correctly.

Our website is cleveradssolutions.com
