### ISSUE TITLE
The code style is not displayed correctly

### ISSUE THREAD

**Issue by clang-clang-clang** [coronalabs/corona-docs#145]
The code style is not displayed correctly, perhaps because the CDN cannot pull the JS file? It started about three days ago.

The JS that failed to load are:

- docs.js
- shCore.js
- shAutoloader.js

All three have the domain name `corona-cdn.coronalabs.com`.

**Comment by Shchvova** [comment]
Thanks so much for reporting it.

**Comment by clang-clang-clang** [comment]
You're welcome.
It has been recovered.
Thank you.
