### ISSUE TITLE
Error in Apple IAP documentation

### ISSUE THREAD

**Issue by AleCGames** [coronalabs/corona-docs#146]
The example in this page [https://docs.coronalabs.com/plugin/apple-iap/canLoadProducts.html](url) have an error. The first line: local store = require( "store" )
does not correspond with the require library that is "plugin.apple.iap" according to the documentation on this page:
https://docs.coronalabs.com/plugin/apple-iap/index.html

**Comment by scottrules44** [comment]
Fixed in docs update, 
thanks for reporting.
