### ISSUE TITLE
Reference to Apple IAP Plugin document

### ISSUE THREAD

**Issue by yosus** [coronalabs/corona-docs#17]
In [Google IAP docs,](http://docs.coronalabs.com/plugin/google-iap-v3/index.html) the link to Apple-IAP is pointing to the old docs.

**Comment by sekodev** [comment]
@yosus is this (https://docs.coronalabs.com/plugin/apple-iap/) the correct one? Does this(http://docs.coronalabs.com/api/library/store/index.html) not work at all?

**Comment by Shchvova** [comment]
They both work. Plugin has some additional functionality.

**Comment by yosus** [comment]
I tested this last month on subscription purchase.

This works [http://docs.coronalabs.com/api/library/store/index.html](url), but  the receipts returned are unreadable

`7b0a0922 7369676e 61747572 6522203d ....`

I think it would be better to just use [https://docs.coronalabs.com/plugin/apple-iap/](url) and have a link to it in [https://docs.coronalabs.com/plugin/index.html](url) (as google and amazon IAP is there)

**Comment by sekodev** [comment]
@yosus, thanks to you, Apple IAP is now referenced in the plugins list. I have plans to add references to it from other IAP plugins as well. I'll also look into other places that I could add reference to it, hopefully in the near future.

**Comment by sekodev** [comment]
Changes made to corona-docs-plugins subrepo and #61 this issue is solved. Thanks for pointing it out @yosus
