### ISSUE TITLE
Android Google IAP Subscription Purchase

### ISSUE THREAD

**Issue by yosus** [coronalabs/corona-docs#18]
For subscription purchases, calling  'store.purchase()' will return an error (see below). 

`Null data in IAB result (response: -1002:Bad response received)`

Will need to use 'store.purchaseSubscription()' which isn't documented, but was seen in the forums.  I have tested it on android subscription and it works. Also note that calling 'store.consumePurchase()' on a subscription item will return an error (see below)

`Items of type 'subs' can't be consumed. (response: -1010:Invalid consumption attempt)`

**Comment by Shchvova** [comment]
Yup.. You can ignore the error. Probably should document it...
