### ISSUE TITLE
IOS: Framework not found FBLPromises

### ISSUE THREAD

**Issue by V4NDER** [coronalabs/corona-docs#26]
Does anyone know how to solve this problem in ios?

ld: Framework not found FBLPromises

**Comment by Shchvova** [comment]
Weird place to ask, but sure. What plugins are you using?

**Comment by V4NDER** [comment]
notifications.v2

**Comment by Shchvova** [comment]
@V4NDER which version of Solar2D/Corona are you using? Does same happens with [3601](https://github.com/coronalabs/corona/releases/tag/3601)?

**Comment by V4NDER** [comment]
I'm using version 3583 because in version 3601 I can't download the plugins (apparently the system doesn't do user authentication)

**Comment by renatosc** [comment]
Seeing same problem with Corona-3573

**Comment by sekodev** [comment]
It's really hard to find your answers here since this is the documentation repo. I'd highly suggest taking this to the Discord channel or the forums.

**Comment by Shchvova** [comment]
Yup.. Also, try using [latest](https://github.com/coronalabs/corona/releases) builds please.

**Comment by renatosc** [comment]
I tried used the latest build but it appears to not download the marketplace plugins anymore...

**Comment by Shchvova** [comment]
Sorry, Corona Labs is closed. Corona Marketplaces does not accept new purchases and will be closed in a month. 
There is several alternative plugins store, like official http://plugins.solar2d.com/
and unofficial http://solar2dmarketplace.com/ and https://www.solar2dplugins.com/
