### ISSUE TITLE
ERROR: configuring 'shared.google.play.services.ads_com.coronalabs' failed! on Android

### ISSUE THREAD

**Issue by laxmansahni** [coronalabs/corona-docs#42]
We integrated AdMob plugin https://marketplace.coronalabs.com/corona-plugins/admob on Android. Build is successful on iOS with Corona SDK Corona-2020.3577/Corona-2020.3583. However, build fails for Android with following error:

> ERROR: configuring 'shared.google.play.services.ads_com.coronalabs' failed!

> FAILURE: Build failed with an exception.
> * Where:
> Build file '/private/var/folders/fv/ncmkw66n02g3j471fmv4nd9h0000gp/T/CLtmpwAmei4/template/app/build.gradle.kts' line: 275
> * What went wrong:
> Could not open dsl remapped class cache for ey6ny8s8m4znsvsu606cxnn4z (/Users/laxmansahni/.gradle/caches/5.4.1/scripts-remapped/corona_41juodkgpmcwy5xg30fkn0jt0/ey6ny8s8m4znsvsu606cxnn4z/dsldcd040730888da95d185715568c9cc57).
>                     > Could not open dsl generic class cache for script '/private/var/folders/fv/ncmkw66n02g3j471fmv4nd9h0000gp/T/CLtmpwAmei4/template/app/build/corona-plugins/shared.google.play.services.ads_com.coronalabs/corona.gradle' (/Users/laxmansahni/.gradle/caches/5.4.1/scripts/ey6ny8s8m4znsvsu606cxnn4z/dsl/dsldcd040730888da95d185715568c9cc57).

Our build.settings file
settings =
{
	orientation =
	{
		-- Supported values for orientation:
        -- portrait, portraitUpsideDown, landscapeLeft, landscapeRight
        
		default ="portrait",
		supported = {"portrait"},
	},

	android =
    {
        applicationChildElements =
        {
            [[
                <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID"
                    android:value="ca-app-pub-xx~xx"/>
            ]],
        },
    },

	 iphone = 
    {
        plist = 
        {
             GADApplicationIdentifier = "ca-app-pub-xx~xx"  
        },
    },
	
    plugins =
    {
        ["plugin.admob"] =
        {
            publisherId = "com.coronalabs"
        },
    },
}

**Comment by Shchvova** [comment]
This is a documentation repository. Please do not open game engine here. Thanks.

**Comment by Shchvova** [comment]
As for the issue, make sure you have Java 8 installed (not java 14,11,12 etc)

**Comment by laxmansahni** [comment]
I've Java 13. I'll install Java 8 & let you know.

**Comment by laxmansahni** [comment]
I installed Java 8 & build is successful.
