### ISSUE TITLE
Error in AdMob Plugin Documentation

### ISSUE THREAD

**Issue by Colin-Morgan** [coronalabs/corona-docs#62]
In the [AdMob Plugin](https://docs.coronalabs.com/plugin/admob/index.html) documentation, under Project Settings>plist>GADApplicationIdentifier, there is a value filled in for the GADApplicationIdentifier. This might be confusing to new users since they should be placing their own AdMob App ID there. 
I suggest replacing the existing AdMob App ID with "[YOUR_ADMOB_APP_ID]" so it is consistent with the instructions in the Android section of the Project Settings.

**Comment by sekodev** [comment]
Done with the [latest commit](https://github.com/coronalabs/corona-docs-plugins/commit/f2d141896234764f3095e3bd51d176bae763f5db) on corona-docs-plugins. Will be fixed the next time documentation updates. Thanks for pointing that out.
