### ISSUE TITLE
Broken and outdated links in documentation

### ISSUE THREAD

**Issue by XeduR** [coronalabs/corona-docs#67]
In https://docs.coronalabs.com/guide/html5/plugins/index.html, there are two references to a VK Direct sample plugin in Bitbucket, but the link is dead. On the same page, there are also support links to the old forums and Slack.

In https://docs.coronalabs.com/api/library/display/loadRemoteImage.html, the sample codes reference an image on Corona Labs' website that no longer exists. This'll result in crashes once the network listeners try to manipulate the images (that don't get created).

**Comment by sekodev** [comment]
Hopefully #68 will solve those issues :)
