### ISSUE TITLE
Por gentileza  postem mais exemplos de aplicação do código! muitos não possuem exemplo de aplicação.

### ISSUE THREAD

**Issue by geogetrindade** [coronalabs/corona-docs#71]

**Comment by Shchvova** [comment]
Thanks fo your suggestion

**Comment by geogetrindade** [comment]
Estou aprendendo a programar em .lua apenas acompanhando a documentação, não é complicado, mas faltam  exemplos de aplicação das opções do código, eu por acaso estou tentando clicar em um botão e através desse evento ocultar ou exibir outros botões a baixo, após um transition no localGroup, se tivermos mais detalhes sera ótimo, uma boa ideia seria uma postagem de trechos pelos próprios usuários que iram servir de referência para os estudantes, parecido com o que a documentação do php faz. Parabéns  pelas Demos que vem no Programa já ajuda bastante obrigado :D

**Comment by Shchvova** [comment]
Got it. Did you try this getting started tutorials? https://docs.coronalabs.com/guide/programming/index.html
