### ISSUE TITLE
Formatting Error on Self-Hosted Plugins Page

### ISSUE THREAD

**Issue by Colin-Morgan** [coronalabs/corona-docs#73]
The Self-Hosted Plugins page has some kind of formatting error where part of the text is superimposed over the page, while everything else scrolls behind it.
https://docs.coronalabs.com/native/hostedPlugin.html

**Comment by Shchvova** [comment]
Thanks. This should be fixed. I also fixed some information.
It seems page can not have two h1 (`#`)... Oh well.
