### ISSUE TITLE
Update Docs for Social Popup plugin not intended for iOS 8+

### ISSUE THREAD

**Issue by jajern** [coronalabs/corona-docs#79]
Consider adding a note to developers in the Social Popup plugin page that this plugin is not for use in Apple iOS 8+. As quoted by Rob further below in the forum, Apple recommends using the Activity plugin.

I coded in the Social Popup not knowing this, and had an error on device that on iOS it never recognizes social apps are installed with native.canShowPopup() method. I am going in now to add code to recognize if Android or iOS and use either depending.

Docs for Social Popup plugin:
https://docs.coronalabs.com/plugin/CoronaProvider_native_popup_social/index.html

Mention by Rob to use Activity plugin for Apple iOS 8+ by Rob:
The social popup on iOS is really a pre-iOS 8 feature. Starting with iOS 8, Apple wants you to use the “Activity” plugin. It’s possible that iOS 11 has in some way broken the the API that canShowPopup depends on.
https://forums.solar2d.com/t/native-canshowpopup-always-returning-false/348130

Thanks

**Comment by sekodev** [comment]
Do you think it would be a good idea to remove iOS from the platforms supported on Social Popup, since iOS 8 is no longer supported, and add a link to the Activity Popup plugin from that page? @Shchvova I'd also like your input on this.

**Comment by sekodev** [comment]
This is long overdue and I'm really sorry about that. It should be fixed when #155 is merged.
