### ISSUE TITLE
alpha

### ISSUE THREAD

**Issue by Andrey5045** [coronalabs/corona-docs#83]
https://docs.coronalabs.com/api/type/DisplayObject/alpha.html

According to the doc **alpha** is a DisplayOblect's feature, but I see that it also works with native objects and only on certain platforms.

Example:
`sn_TB = native.newTextField(x, y, R_width_int, TB_height_int)`

E.g. in emulator on Windows this will not work:
`sn_TB.alpha = 0`

This will not work too:

```
transition.to(
	sn_TB,
	{time = 250,
	alpha = 1}
	)
```

It gives an error:
WARNING: D:\a\corona\corona\subrepos\transition\transition.lua:XXX: Native UI objects on Windows do not support the "alpha" property.

But, on Android device the transition works smoothly! I guess, this is undocumented feature of alpha which got to be added to the official docs. (I am not sure about iPhones...) Thanks.

**Comment by Shchvova** [comment]
Native objects are [DisplayObjects](https://docs.coronalabs.com/api/type/DisplayObject/index.html) too. They are not ShapeObjects which are descendant from [DisplayObjects](https://docs.coronalabs.com/api/type/ShapeObject/index.html).
DispayObjects have properties for position and visibility (alpha). 
ShapeObjects - fill, strokes etc

Alpha is a little tricky one. It propagates to color for shape objects but for some other objects like native it is basically 0 for invisible and visible is >0

**Comment by Andrey5045** [comment]
Yet another gotcha to learn. Thanks.
