### ISSUE TITLE
Some additional requirements in Solar2D documentation

### ISSUE THREAD

**Issue by AleCGames** [coronalabs/corona-docs#88]
As in the previous Google Play Games Services plugin, the addition of the following code is required in order to use the Google Play Games Services from Google, but the documentation of the new version of the plugin (plugin.gpgs.v2) does not contain this part:

_Additionally, you must specify the Google Play Games App ID in the android table of build.settings as the googlePlayGamesAppId key:_
`
settings = {
 
    android =
    {
        googlePlayGamesAppId = "YOUR_APPLICATION_ID",
    },
}
`

**Comment by sekodev** [comment]
Thank you for pointing this out. Updated GPGS-v2 documentation in corona-docs-plugins repo. Probably, it'll go live with the next docs update.

**Comment by AleCGames** [comment]
> Thank you for pointing this out. Updated GPGS-v2 documentation in corona-docs-plugins repo. Probably, it'll go live with the next docs update.

Thank you!

**Comment by scottrules44** [comment]
This has been added already
