### ISSUE TITLE
Add documentation for the new transition.loop method 

### ISSUE THREAD

**Issue by depilz** [coronalabs/corona-docs#96]
I'm going to add this later, it's just a reminder.

**Comment by sekodev** [comment]
@depilz I took the liberty to create the page. Can you take a look at it to see if it's OK?

**Comment by depilz** [comment]
Thank you so much @sekodev ! I completely forgot about this, I think only the overview is wrong. We could use something like:

```
Similar to [transition.to()](https://docs.coronalabs.com/api/library/transition/to.html) except that this starts and ends at the same position creating a loop.

The given time is for a full cycle and the easing is reversed in the second half of the transition.
```

**Comment by sekodev** [comment]
Sorry about that. This was basically a copy paste job to keep this documented and I forgot that one thing I need to change 😄 I'll send a fix to it right away.

**Comment by sekodev** [comment]
@depilz can you check #122 to see if it is better?
