### ISSUE TITLE
App Keystore Not Working in Solar SDK

### ISSUE THREAD

**Issue by waynebrain** [coronalabs/corona-docs#97]
When i try and build my app it asks for my keystore but even if I input a valid password and keystore i still receive error saying "Keystore password not valid"

Please fix this

**Comment by XeduR** [comment]
This is the Solar2D Docs repo.

Also, this is an issue that you should post about to [Solar2D forums](https://forums.solar2d.com/). The issue is somewhere with your setup, so when you create a forum post, please post your full console log there as well.
